export const IPC = {
  bootstrap: "app:bootstrap",
  tabSave: "tabs:save",
  tabCreate: "tabs:create",
  tabDelete: "tabs:delete",
  tabSaveAndApply: "tabs:save-and-apply",
  hostsImport: "hosts:import",
  backupsList: "backups:list",
  backupsCreate: "backups:create",
  backupsRead: "backups:read",
  backupsRestore: "backups:restore",
  backupsDelete: "backups:delete",
  backupsExport: "backups:export",
  backupsOpen: "backups:open",
  settingsSave: "settings:save",
  updateCheck: "update:check",
  updateOpen: "update:open",
  fullscreen: "window:fullscreen",
} as const;
